notifications:
  email:
    on_success: always # default: always
    on_failure: always # default: always
  recipients:
    - one@example.com

language: java

before_install:
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
 - mvn test -B

jdk:
  - oraclejdk9
  - openjdk8
